#!/usr/bin/env bash

set -eu
ROOT="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"

bash -n "$ROOT/tmux-drudwyn.tmux" "$ROOT"/scripts/*.sh "$ROOT"/tests/*.sh
bash "$ROOT/tests/rename_test.sh"
bash "$ROOT/tests/icons_test.sh"
"$ROOT/tests/classify_test.sh"
"$ROOT/tests/help_test.sh"
"$ROOT/tests/status_bar_test.sh"
"$ROOT/tests/integration_test.sh"
"$ROOT/tests/worktree_test.sh"
"$ROOT/tests/cockpit_test.sh"
"$ROOT/tests/v2_test.sh"
bash "$ROOT/tests/start_failure_test.sh"
bash "$ROOT/tests/batch_test.sh"
python3 "$ROOT/tests/batch_ui_test.py"
python3 "$ROOT/tests/worker_launch_test.py"
python3 "$ROOT/tests/recovery_test.py"
python3 "$ROOT/tests/worker_integration_test.py"
python3 "$ROOT/tests/conflict_test.py"
python3 "$ROOT/tests/verification_test.py"
python3 "$ROOT/tests/global_cockpit_test.py"
python3 "$ROOT/tests/status_a_test.py"
bash "$ROOT/tests/lifecycle_test.sh"
python3 "$ROOT/tests/activity_test.py"
python3 "$ROOT/tests/navigator_test.py"
python3 "$ROOT/tests/independent_navigation_test.py"
python3 "$ROOT/tests/settings_test.py"
"$ROOT/tests/privacy_test.sh"
"$ROOT/tests/package_test.sh"
"$ROOT/tests/release_workflow_test.sh"
