pub mod ambient;
pub mod batch;
mod brand;
pub mod cockpit;
pub mod config;
pub mod coordinator;
pub mod discovery;
pub mod domain;
mod icons;
pub mod inventory;
pub mod lifecycle;
pub mod navigation;
pub mod navigator;
mod persistence;
pub mod recovery;
pub mod session;
pub mod session_navigator;
pub mod settings;
pub mod theme;
mod ui;
pub mod workspace;
